services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 1024M

    environment:
      POSTGRES_DB: servi-track
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: