spring:
  application:
    name: servi-track
  datasource:
    url: jdbc:postgresql://localhost:5432/servi-track
    username: dev
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true